### ISSUE TITLE
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.

### ISSUE THREAD

**Issue by rgarrigue** [peter-evans/repository-dispatch#251]
Hi there

Here's a warning out of my CI

```
Run peter-evans/repository-dispatch@v2
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (/runner/_work/_actions/peter-evans/repository-dispatch/v2/dist/index.js:4221:21)
    at hasErrorStatus (/runner/_work/_actions/peter-evans/repository-dispatch/v2/dist/index.js:43:25)
    at /runner/_work/_actions/peter-evans/repository-dispatch/v2/dist/index.js:71:17
    at Generator.throw (<anonymous>)
    at rejected (/runner/_work/_actions/peter-evans/repository-dispatch/v2/dist/index.js:32:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Cheers,

**Comment by peter-evans** [comment]
Hi @rgarrigue 

This is fixed in the latest version `v2.1.2` / `v2`.

Thank you!
