### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by spvkgn** [peter-evans/repository-dispatch#256]
Worked fine until today - this error occurs:

<details>
<summary>Details</summary>

```
2023-09-07T02:58:10.4075808Z ##[group]Run peter-evans/repository-dispatch@v2
2023-09-07T02:58:10.4076214Z with:
2023-09-07T02:58:10.4076802Z   token: ***
2023-09-07T02:58:10.4077143Z   repository: spvkgn/far2l-openwrt
2023-09-07T02:58:10.4077511Z   event-type: build-nightly
2023-09-07T02:58:10.4078332Z   client-payload: {
  "repo": "elfmz/far2l",
  "date": "20230906",
  "sha": "be37138",
  "url": "https://github.com/elfmz/far2l/commit/be37138447506f3a8a6188900effb35e5eae25a1",
  "tag": "2.5.2",
  "message": "Merge pull request #1825 from akruphi/master

Command prefix `far:` and draft `far:about` command"
}

2023-09-07T02:58:10.4079111Z env:
2023-09-07T02:58:10.4079379Z   REPO: elfmz/far2l
2023-09-07T02:58:10.4079673Z ##[endgroup]
2023-09-07T02:58:10.6439623Z ##[debug]Inputs: {
2023-09-07T02:58:10.6440372Z ##[debug]  token: '***',
2023-09-07T02:58:10.6440763Z ##[debug]  repository: 'spvkgn/far2l-openwrt',
2023-09-07T02:58:10.6441194Z ##[debug]  eventType: 'build-nightly',
2023-09-07T02:58:10.6441589Z ##[debug]  clientPayload: '{\n' +
2023-09-07T02:58:10.6441983Z ##[debug]    '  "repo": "elfmz/far2l",\n' +
2023-09-07T02:58:10.6442573Z ##[debug]    '  "date": "20230906",\n' +
2023-09-07T02:58:10.6442906Z ##[debug]    '  "sha": "be37138",\n' +
2023-09-07T02:58:10.6443856Z ##[debug]    '  "url": "https://github.com/elfmz/far2l/commit/be37138447506f3a8a6188900effb35e5eae25a1",\n' +
2023-09-07T02:58:10.6444376Z ##[debug]    '  "tag": "2.5.2",\n' +
2023-09-07T02:58:10.6444814Z ##[debug]    '  "message": "Merge pull request #1825 from akruphi/master\n' +
2023-09-07T02:58:10.6445237Z ##[debug]    '\n' +
2023-09-07T02:58:10.6445649Z ##[debug]    'Command prefix `far:` and draft `far:about` command"\n' +
2023-09-07T02:58:10.6446041Z ##[debug]    '}'
2023-09-07T02:58:10.6446314Z ##[debug]}
2023-09-07T02:58:10.6459462Z ##[debug]SyntaxError: Unexpected token 
2023-09-07T02:58:10.6459885Z ##[debug] in JSON at position 236
2023-09-07T02:58:10.6460303Z ##[debug]    at JSON.parse (<anonymous>)
2023-09-07T02:58:10.6460809Z ##[debug]    at /home/runner/work/_actions/peter-evans/repository-dispatch/v2/dist/index.js:70:38
2023-09-07T02:58:10.6461330Z ##[debug]    at Generator.next (<anonymous>)
2023-09-07T02:58:10.6461854Z ##[debug]    at /home/runner/work/_actions/peter-evans/repository-dispatch/v2/dist/index.js:38:71
2023-09-07T02:58:10.6462365Z ##[debug]    at new Promise (<anonymous>)
2023-09-07T02:58:10.6462939Z ##[debug]    at __webpack_modules__.3109.__awaiter (/home/runner/work/_actions/peter-evans/repository-dispatch/v2/dist/index.js:34:12)
2023-09-07T02:58:10.6464039Z ##[debug]    at run (/home/runner/work/_actions/peter-evans/repository-dispatch/v2/dist/index.js:55:12)
2023-09-07T02:58:10.6464727Z ##[debug]    at Object.3109 (/home/runner/work/_actions/peter-evans/repository-dispatch/v2/dist/index.js:84:1)
2023-09-07T02:58:10.6465750Z ##[debug]    at __nccwpck_require__ (/home/runner/work/_actions/peter-evans/repository-dispatch/v2/dist/index.js:9753:43)
2023-09-07T02:58:10.6466435Z ##[debug]    at /home/runner/work/_actions/peter-evans/repository-dispatch/v2/dist/index.js:9773:37
2023-09-07T02:58:10.6514162Z ##[error]Unexpected token 
 in JSON at position 236
2023-09-07T02:58:10.6529369Z ##[debug]Node Action run completed with exit code 1
2023-09-07T02:58:10.6678222Z ##[debug]Finishing: Dispatch event to remote repository
```

</details>

**Comment by peter-evans** [comment]
Hi @spvkgn 

The JSON parser is complaining because you have a multiline string for the `message` property. I think you need to replace the line breaks with `\n` before setting it in the payload.
